# Generated by Django 3.1.2 on 2020-11-10 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_tour'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hotel',
            table='hotels',
        ),
    ]
